dist: xenial
sudo: required
language: node_js
node_js:
- node
- '10'
- '8'
before_install:
- sudo apt-get install p7zip-full xterm
install:
- npm install --global npm@4
- npm install
services:
- xvfb
before_script:
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
script:
- npm test
- npm run build:src
addons:
  chrome: stable
  firefox: latest

jobs:
  include:
    - stage: Release prebuilt binaries
      node_js: '10'
      echo: 'Deploying prebuilt binaries...'
      script: npm run build
      before_deploy:
        - |
          echo "Travis tag was $TRAVIS_TAG"

          if ! [[ $DEPLOY_STEP ]]; then
            export DEPLOY_STEP=1
            echo 'About to deploy new tag'
          else
            # About to deploy latest-manifest
            export DEPLOY_STEP=2
            echo 'About to deploy manifest update'
            export TRAVIS_TAG=latest-manifest
          fi

          echo "Travis tag is $TRAVIS_TAG"
      deploy:
        - provider: releases
          api_key:
            secure: BS5tc2PhyIKsw048EG8TxT5HB/EymS8javixTzdpo18+f0BngDfHaTGD9DrXOzepv+4amTdzy0j7K9TdepejMuRDbg+Z3+8IkD0BefqvnnmZZv4ZQFiIdv5VXsAfS9vj0QOOAAwA/oz9rVdA9BEIN/8MNAXClSUT66ciaHLcBq6sr1N9ZEdqaDSYs8UiBEwA7Qnk6Q2/9EuGGozMNrOH5hlyiP0eKtjn4q/PemdBzemGx5KNWFr5zVVYy8kaMB/ELboOUB0AufaOyexsGWJdXSJwOdWUTYWqKsGGXXzdjcW/AT+8tGr968WNmGvg/d2SI2mIbJKrHVk8lc3tbyVfxngUbpZnHMmqtf3JSgTKeIeBMUlrVsh0gUiOU4yYkK2jITqsliREtrZ/ik9QEkw2VXh90A+iUBzeDhHACvPpA8JlPwwtFWu34zdHOyXk/3kVUDINQkVorQ2txwa2yc68a4nbptprHKUqafG0qw8TIViY16T8cZLm0QYJ9hLI1grBR8D9YpqJysSZcJrhUi/GWppzOZm5X0nxd0zvhG1KbmtIc9UgfoUA8rA2srmR9LEhptmWHCVzOeb1WEovm6cV6iKKUnq9jmbYSJPUuiDQPrUeSSGZneRb9rwHXh6Hg2rTo7R3l97/DPPTNF+q0k+qQrXqPvWZk837VmIVaSiMc/8=
          file_glob: true
          tag_name: $TRAVIS_TAG
          file: dist/v*/*
          skip_cleanup: true
          on:
            repo: httptoolkit/httptoolkit-server
            tags: true
        - provider: releases
          api_key:
            secure: BS5tc2PhyIKsw048EG8TxT5HB/EymS8javixTzdpo18+f0BngDfHaTGD9DrXOzepv+4amTdzy0j7K9TdepejMuRDbg+Z3+8IkD0BefqvnnmZZv4ZQFiIdv5VXsAfS9vj0QOOAAwA/oz9rVdA9BEIN/8MNAXClSUT66ciaHLcBq6sr1N9ZEdqaDSYs8UiBEwA7Qnk6Q2/9EuGGozMNrOH5hlyiP0eKtjn4q/PemdBzemGx5KNWFr5zVVYy8kaMB/ELboOUB0AufaOyexsGWJdXSJwOdWUTYWqKsGGXXzdjcW/AT+8tGr968WNmGvg/d2SI2mIbJKrHVk8lc3tbyVfxngUbpZnHMmqtf3JSgTKeIeBMUlrVsh0gUiOU4yYkK2jITqsliREtrZ/ik9QEkw2VXh90A+iUBzeDhHACvPpA8JlPwwtFWu34zdHOyXk/3kVUDINQkVorQ2txwa2yc68a4nbptprHKUqafG0qw8TIViY16T8cZLm0QYJ9hLI1grBR8D9YpqJysSZcJrhUi/GWppzOZm5X0nxd0zvhG1KbmtIc9UgfoUA8rA2srmR9LEhptmWHCVzOeb1WEovm6cV6iKKUnq9jmbYSJPUuiDQPrUeSSGZneRb9rwHXh6Hg2rTo7R3l97/DPPTNF+q0k+qQrXqPvWZk837VmIVaSiMc/8=
          file_glob: true
          tag_name: latest-manifest # Fixed release, updated with the latest manifests each time
          overwrite: true
          file: dist/latest-manifest/*
          skip_cleanup: true
          on:
            repo: httptoolkit/httptoolkit-server
            tags: true